spring:
  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: reservationGroup
      key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      value-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      bootstrap-servers: kafka:29092
    producer:
      key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      value-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      bootstrap-servers: kafka:29092
    template:
      default-topic: reservation

server:
  port: 8080